services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-car-wash-website
    container_name: frontend-car-wash-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    working_dir: /usr/src/app
    command: npm start
